# Generated by Django 5.2.1 on 2025-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoexcluidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('apo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('apo_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('apo_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('apo_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('apo_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('apo_mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
